Repository openshift-eng/baremetal-qe-infra, pull requests merged in 2023-10, with the labels that each got.

#15 OCPQE-15780: Add dhcp container as a service
  images/dhcp/Containerfile
  images/fcos-bastion-image/Containerfile
  images/fcos-bastion-image/root/usr/bin/dhcp-init.sh
  images/fcos-bastion-image/root/usr/bin/fcos-download.sh
  images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset
  images/fcos-bastion-image/root/usr/lib/systemd/system/dhcp-init.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/dhcp.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/fcos-download.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/fcos-download.timer
  images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/dhcp_systemd.conf
  images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/dnsmasq.conf
  images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/tftpboot/grub.cfg
  images/fcos-bastion-image/root/usr/share/bastion_services/ignitions/shell.bu
  images/fcos-bastion-image/root/usr/share/bastion_services/ignitions/wipe_disks.bu
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#22 Remove comments
  images/dhcp/Containerfile
Labels: approved, lgtm

#23 OCPQE-16616: Adding missing tang.service enabled preset
  images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset
Labels: approved, lgtm, needs-ok-to-test, jira/valid-reference

#24 Use centos 9 base image for dnsmasq
  images/dhcp/Containerfile
Labels: approved, lgtm

#25 Remove copy line from tang containerfile
  images/dhcp/Containerfile
  images/dhcp/root/.gitkeep
  images/tang/Containerfile
  images/tang/root/.gitkeep
Labels: approved, lgtm
