Repository openshift-eng/baremetal-qe-infra, pull requests merged in 2024-07, with the labels that each got.

#67 Add ipv6 vips reservation
  images/fcos-bastion-image/root/usr/bin/reserve-hosts.sh
Labels: approved, lgtm

#69 OCPQE-23078: setup an expiry date for persistent clusters
  images/fcos-bastion-image/root/usr/bin/clean-up.sh
Labels: approved, lgtm, jira/valid-reference

#70 Fix var for firewalled cluster and export arch
  images/prow-image/root/usr/bin/deprovision.sh
Labels: approved, lgtm

#72 update aarch64 to arm64
  images/prow-image/root/usr/bin/deprovision.sh
Labels: approved, lgtm

#73 OCPQE-20708: Increase retrials and delay between health-checks for registry@
  images/fcos-bastion-image/root/usr/lib/systemd/system/registry@.service
Labels: approved, jira/valid-reference

#76 Prune clusters older than 24 hours
  images/fcos-bastion-image/root/usr/bin/clean-up.sh
Labels: approved, lgtm
