Repository openshift-eng/baremetal-qe-infra, pull requests merged in 2024-01, with the labels that each got.

#41 OCPQE-18445: Podman containers healthcheck
  images/fcos-bastion-image/root/usr/bin/print-net-env.sh
  images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset
  images/fcos-bastion-image/root/usr/lib/systemd/system/bind9.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/fill-network-env.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/nginx.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/registry@.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/squid-proxy.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/tang.service
Labels: approved, jira/valid-reference

#43 Script to prepare host for boot and power on
  images/fcos-bastion-image/root/usr/bin/prepare_host_for_boot
Labels: approved

#40 [OCPQE-13828] - Reserve Bare Metal servers by Vendor
  images/fcos-bastion-image/root/usr/bin/reserve-hosts.sh
Labels: approved, lgtm

#48 [OCPQE-18644] - use ipxe on hpe arm servers only when boot mode is pxe
  images/fcos-bastion-image/root/usr/bin/prepare_host_for_boot
Labels: approved, lgtm

#44 OCPQE-18643: Add python3 deps required to run pruning
  images/fcos-bastion-image/Containerfile
Labels: approved, lgtm, jira/valid-reference

#45 OCPQE-18500: use dhcp-hostsdir=<path> in dnsmasq for dynamic updates
  images/fcos-bastion-image/root/usr/bin/dhcp-init.sh
  images/fcos-bastion-image/root/usr/lib/systemd/system/dhcp.service
  images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/dnsmasq.conf
Labels: approved, lgtm, jira/valid-reference

#50 OCPQE-18422: Add oneshot service to configure podman v6 network
  images/fcos-bastion-image/root/etc/containers/networks/podman.json
Labels: approved, lgtm, jira/valid-reference
