Repository openshift-eng/baremetal-qe-infra, pull requests merged in 2024-08, with the labels that each got.

#75 Reset dhcp config on starts and add in use dhcp-options
  images/fcos-bastion-image/root/usr/lib/systemd/system/dhcp-init.service
  images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/dnsmasq.conf
Labels: approved, lgtm, do-not-merge/hold

#77 Add 'set -x' and wipefs of devices with wildcard
  images/fcos-bastion-image/root/usr/share/bastion_services/ignitions/wipe_disks.bu
Labels: approved, lgtm

#78 Add lshw and pciutils to the base fcos image
  images/fcos-base-image/Containerfile
Labels: approved

#79 Avoid infinite loop for node power off
  images/fcos-bastion-image/root/usr/bin/prepare_host_for_boot
Labels: approved, lgtm

#80 fix nmin incorrect argument
  images/fcos-bastion-image/root/usr/bin/clean-up.sh
Labels: approved, lgtm
