Repository openshift-eng/baremetal-qe-infra, pull requests merged in 2024-02, with the labels that each got.

#52 OCPQE-19170: Add timer unit for registries cleanup
  images/fcos-bastion-image/root/usr/bin/clean-registries.sh
  images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset
  images/fcos-bastion-image/root/usr/lib/systemd/system/clean-registries.service
  images/fcos-bastion-image/root/usr/lib/systemd/system/clean-registries.timer
Labels: approved, lgtm, jira/valid-reference

#51 OCPQE-15774: Fix pruning
  images/fcos-bastion-image/root/usr/bin/clean-up.sh
  images/fcos-bastion-image/root/usr/bin/prune_nodes
  images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset
  images/prow-image/Dockerfile
  images/prow-image/root/usr/bin/deprovision.sh
Labels: approved, jira/valid-reference

#54 include ipi dir for sparse checkout
  images/prow-image/root/usr/bin/deprovision.sh
Labels: approved, lgtm

#56 Remove dhcp-boot, use dhcp option 67 (bootfile-name)
  images/fcos-bastion-image/root/usr/share/bastion_services/dhcp/dnsmasq.conf
Labels: approved, lgtm

#59 Disable libvirt default network
  images/fcos-base-image/root/usr/bin/libvirt_init.sh
Labels: approved, lgtm

#60 OCPQE-19722: Fix registry@.service healthchecks
  images/fcos-bastion-image/root/usr/lib/systemd/system/registry@.service
Labels: approved, jira/valid-reference

#57 OCPQE-19642: Fix cleanup issue of container images in mirror registries
  images/fcos-bastion-image/root/usr/bin/clean-registries.sh
  images/fcos-bastion-image/root/usr/lib/systemd/system-preset/98-bastion.preset
Labels: approved, lgtm, jira/valid-reference
